# fly.toml app configuration file generated for neo4j on 2024-01-17T11:13:32Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "neo4j"
primary_region = "lhr"

[build]
  image = "neo4j"

[[mounts]]
  source = "data"
  destination = "/data"
  auto_extend_size_threshold = 0

[http_service]
  internal_port = 7474
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[services]]
  internal_port = 7687
  protocol = "tcp"
  [[services.ports]]
    handlers = ["tls"]
    port = 7687

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
